### ISSUE TITLE
Resizable code window makes the globe disappear

### ISSUE THREAD

**Issue by emackey** [adi2412/cesium#3]
The "Knockout" branch has a resizable code editor window, but resizing it larger often makes the globe window disappear, and sizing it smaller makes the globe reappear.

**Comment by emackey** [comment]
Also, when viewing a documentation tab or "white" content in Cesium, there's no discernible border between the left and right windows.  There should be more of a visual edge here, even if both windows have white backgrounds, plus some indication that the user is able to grab and drag the edge.

**Comment by adi2412** [comment]
Fixed in b6de1effa53ff67b3092e101e28225d5828d9f3f and 7e4a531ca496c2fff7ffbda029f3bf2b58997003

**Comment by emackey** [comment]
I can still get the globe to disappear, even in Hello World just by dragging the editor to the right.  Chrome on Win 7.

**Comment by adi2412** [comment]
Are you sure about this? I'm not able to replicate this issue. It shouldn't be happening after the fix, since the min width is specified.

**Comment by emackey** [comment]
This was still broken for me on the GSoC pencils-down date, but appears to have been subsequently fixed in 850857d23.

**Comment by adi2412** [comment]
To be honest, I'm not sure that's even possible. Looking at the commit, the fix for this was in b6de1effa53ff67b3092e101e28225d5828d9f3f. I'm not sure how the recent commit could have fixed this.
